'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { api } from '@/lib/api';
import { CompanyReport, SECTIONS } from '@/types';
import { VisualizationRenderer } from '@/components/visualizations';
import { formatDate } from '@/lib/utils';
import '@/styles/print.css';

export default function PrintReportPage() {
  const params = useParams();
  const researchId = params.id as string;
  const [report, setReport] = useState<CompanyReport | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadReport() {
      try {
        const data = await api.getFullReport(researchId);
        setReport(data);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to load report');
      }
    }
    loadReport();
  }, [researchId]);

  if (error) {
    return <div className="p-8 text-red-600">{error}</div>;
  }

  if (!report) {
    return <div className="p-8">Loading report...</div>;
  }

  return (
    <div className="print-report max-w-4xl mx-auto p-8 bg-white">
      {/* Header */}
      <header className="print-header mb-8 pb-4 border-b-2 border-gray-300">
        <h1 className="text-3xl font-bold text-gray-900">{report.company_name}</h1>
        <p className="text-lg text-gray-600">Due Diligence Report</p>
        <p className="text-sm text-gray-500 mt-2">
          Generated: {formatDate(report.created_at)}
        </p>
      </header>

      {/* Table of Contents */}
      <nav className="mb-8 p-4 bg-gray-50 rounded-lg">
        <h2 className="text-lg font-semibold mb-3">Table of Contents</h2>
        <ol className="list-decimal pl-6 space-y-1">
          {SECTIONS.map((section, index) => (
            <li key={section.id}>
              <a href={`#section-${section.id}`} className="text-blue-600 hover:underline">
                {section.name}
              </a>
            </li>
          ))}
        </ol>
      </nav>

      {/* Sections */}
      {SECTIONS.map((sectionConfig) => {
        const section = report.sections[sectionConfig.id];
        if (!section) return null;

        return (
          <section
            key={sectionConfig.id}
            id={`section-${sectionConfig.id}`}
            className="section mb-12"
          >
            <h2 className="text-2xl font-bold text-gray-900 mb-4 pb-2 border-b border-gray-200">
              {section.section_name}
            </h2>

            {/* Visualization */}
            {sectionConfig.hasVisualization && section.visualization_data && (
              <div className="chart-container mb-6">
                <VisualizationRenderer
                  sectionId={sectionConfig.id}
                  data={section.visualization_data}
                />
              </div>
            )}

            {/* Content */}
            {section.formatted_content ? (
              <div
                className="prose max-w-none"
                dangerouslySetInnerHTML={{ __html: formatContent(section.formatted_content) }}
              />
            ) : (
              <p className="text-gray-500 italic">Content not available.</p>
            )}

            {/* Sources */}
            {section.sources.length > 0 && (
              <div className="mt-6 pt-4 border-t border-gray-200">
                <h3 className="text-sm font-semibold text-gray-700 mb-2">Sources</h3>
                <ul className="text-xs text-gray-600 space-y-1">
                  {section.sources.map((source, index) => (
                    <li key={index} className="source-citation">
                      [{index + 1}] {source.title} - {source.url}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </section>
        );
      })}

      {/* Footer */}
      <footer className="print-footer mt-12 pt-4 border-t border-gray-300 text-center text-sm text-gray-500">
        <p>Due Diligence Report - {report.company_name}</p>
        <p>Generated by AI-Powered Due Diligence Platform</p>
      </footer>
    </div>
  );
}

function formatContent(content: string): string {
  return content
    .replace(/^### (.*$)/gim, '<h3>$1</h3>')
    .replace(/^## (.*$)/gim, '<h2>$1</h2>')
    .replace(/^# (.*$)/gim, '<h1>$1</h1>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/^- (.*$)/gim, '<li>$1</li>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>');
}
